# Generated by Django 4.2.7 on 2023-12-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComerAqui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesas',
            name='descripcion',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
