# Generated by Django 4.2.7 on 2023-12-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComerAqui', '0002_alter_mesas_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesas',
            name='id',
        ),
        migrations.AlterField(
            model_name='mesas',
            name='numero_mesa',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
